/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.divesafe.application;

import ca.mcgill.ecse.divesafe.javafx.fxml.DiveSafeFxmlView;
import ca.mcgill.ecse.divesafe.model.DiveSafe;
import ca.mcgill.ecse.divesafe.persistence.DiveSafePersistence;
import javafx.application.Application;

/**
 * The methods in this class were adapted from the BTMS version of the
 * Application class (provided in tutorials)
 * 
 * @author rarchambault (Roxanne Archambault)
 *
 */
public class DiveSafeApplication {
	private static DiveSafe diveSafe;

	public static final boolean BLUE_MODE = true;

	/**
	 * Main entry point.
	 *
	 * @param args
	 */
	public static void main(String[] args) {
		// start UI
		Application.launch(DiveSafeFxmlView.class, args);
	}

	public static DiveSafe getDiveSafe() {
		if (diveSafe == null) {
			// these attributes are default, you should set them later with the setters
			diveSafe = DiveSafePersistence.load();
		}

		return diveSafe;
	}
}
